import type { CarFeature } from "~/types/types";

export const CAR_FEATURE_LABELS: Record<CarFeature, string> = {
  power_windows: "Power Windows",
  power_steering: "Power Steering",
  air_conditioning: "Air Conditioning",
  climate_control: "Climate Control",
  dual_zone_climate: "Dual-Zone Climate",
  tri_zone_climate: "Tri-Zone Climate",
  heated_seats: "Heated Seats",
  ventilated_seats: "Ventilated Seats",
  heated_steering_wheel: "Heated Steering Wheel",
  leather_seats: "Leather Seats",
  memory_seats: "Memory Seats",
  power_adjustable_seats: "Power Adjustable Seats",
  auto_dimming_mirrors: "Auto-Dimming Mirrors",
  rain_sensing_wipers: "Rain-Sensing Wipers",
  ambient_lighting: "Ambient Lighting",
  rear_window_sunshade: "Rear Window Sunshade",
  navigation: "Navigation",
  bluetooth: "Bluetooth",
  usb_ports: "USB Ports",
  wireless_charging: "Wireless Charging",
  apple_carplay: "Apple CarPlay",
  android_auto: "Android Auto",
  touchscreen_display: "Touchscreen Display",
  voice_control: "Voice Control",
  premium_sound_system: "Premium Sound System",
  rear_seat_entertainment: "Rear Seat Entertainment",
  digital_instrument_cluster: "Digital Instrument Cluster",
  head_up_display: "Head-Up Display",
  cruise_control: "Cruise Control",
  adaptive_cruise_control: "Adaptive Cruise Control",
  lane_assist: "Lane Assist",
  lane_keep_assist: "Lane Keep Assist",
  lane_departure_warning: "Lane Departure Warning",
  blind_spot_monitor: "Blind Spot Monitor",
  forward_collision_warning: "Forward Collision Warning",
  automatic_emergency_braking: "Automatic Emergency Braking",
  pedestrian_detection: "Pedestrian Detection",
  traffic_sign_recognition: "Traffic Sign Recognition",
  driver_attention_monitor: "Driver Attention Monitor",
  parking_sensors: "Parking Sensors",
  rear_camera: "Rear Camera",
  "360_camera": "360° Camera",
  night_vision: "Night Vision",
  cross_traffic_alert: "Cross Traffic Alert",
  led_headlights: "LED Headlights",
  matrix_led_headlights: "Matrix LED Headlights",
  adaptive_lights: "Adaptive Lights",
  automatic_headlights: "Automatic Headlights",
  fog_lights: "Fog Lights",
  daytime_running_lights: "Daytime Running Lights",
  cornering_lights: "Cornering Lights",
  keyless_entry: "Keyless Entry",
  keyless_start: "Keyless Start",
  remote_start: "Remote Start",
  digital_key: "Digital Key",
  alarm_system: "Alarm System",
  engine_immobilizer: "Engine Immobilizer",
  gps_tracking: "GPS Tracking",
  drive_modes: "Drive Modes",
  sport_mode: "Sport Mode",
  eco_mode: "Eco Mode",
  adaptive_suspension: "Adaptive Suspension",
  air_suspension: "Air Suspension",
  limited_slip_differential: "Limited Slip Differential",
  paddle_shifters: "Paddle Shifters",
  launch_control: "Launch Control",
  start_stop_system: "Start/Stop System",
  sunroof: "Sunroof",
  panoramic_roof: "Panoramic Roof",
  power_tailgate: "Power Tailgate",
  hands_free_tailgate: "Hands-Free Tailgate",
  roof_rails: "Roof Rails",
  tow_package: "Tow Package",
  trailer_assist: "Trailer Assist",
  running_boards: "Running Boards",
  alloy_wheels: "Alloy Wheels",
  performance_tires: "Performance Tires",
  all_season_tires: "All-Season Tires",
  run_flat_tires: "Run-Flat Tires",
  spare_tire: "Spare Tire",
  tire_pressure_monitoring: "TPMS",
  regenerative_braking: "Regenerative Braking",
  battery_preconditioning: "Battery Preconditioning",
  fast_charging: "Fast Charging",
  home_charging_cable: "Home Charging Cable",
  range_estimator: "Range Estimator",
  energy_consumption_display: "Energy Consumption Display",
};


export const CAR_FEATURE_GROUPS: Record<
  string,
  { title: string; features: CarFeature[] }
> = {
  comfort: {
    title: "Comfort & Convenience",
    features: [
      "power_windows",
      "power_steering",
      "air_conditioning",
      "climate_control",
      "dual_zone_climate",
      "tri_zone_climate",
      "heated_seats",
      "ventilated_seats",
      "heated_steering_wheel",
      "leather_seats",
      "memory_seats",
      "power_adjustable_seats",
      "ambient_lighting",
      "rear_window_sunshade",
    ],
  },

  infotainment: {
    title: "Infotainment & Connectivity",
    features: [
      "navigation",
      "bluetooth",
      "usb_ports",
      "wireless_charging",
      "apple_carplay",
      "android_auto",
      "touchscreen_display",
      "voice_control",
      "premium_sound_system",
      "digital_instrument_cluster",
      "head_up_display",
    ],
  },

  safety: {
    title: "Safety & Driver Assistance",
    features: [
      "cruise_control",
      "adaptive_cruise_control",
      "lane_keep_assist",
      "blind_spot_monitor",
      "forward_collision_warning",
      "automatic_emergency_braking",
      "parking_sensors",
      "rear_camera",
      "360_camera",
      "cross_traffic_alert",
    ],
  },

  exterior: {
    title: "Exterior & Utility",
    features: [
      "sunroof",
      "panoramic_roof",
      "power_tailgate",
      "hands_free_tailgate",
      "roof_rails",
      "tow_package",
    ],
  },

  performance: {
    title: "Performance & Driving",
    features: [
      "drive_modes",
      "sport_mode",
      "eco_mode",
      "adaptive_suspension",
      "air_suspension",
      "paddle_shifters",
      "launch_control",
    ],
  },
};