name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Run Tests
        run: npm run test

      - name: Build Application
        run: npm run build
        env:
          NODE_ENV: production
          VITE_FIREBASE_API_KEY: "mock_api_key_for_ci_build_only_123456789"
          VITE_FIREBASE_AUTH_DOMAIN: "mock.firebaseapp.com"
          VITE_FIREBASE_PROJECT_ID: "mock-project-id"
          VITE_FIREBASE_STORAGE_BUCKET: "mock-bucket"
          VITE_FIREBASE_MESSAGING_SENDER_ID: "123456789"
          VITE_FIREBASE_APP_ID: "1:123:web:mock-app-id"
